[global]
    workgroup = WORKGROUP
    server string = LibraryIT Server
    security = user
    map to guest = never
    
    # Konfigurasi dasar untuk audit logging
    vfs objects = full_audit
    full_audit:prefix = %u|%m|%S
    full_audit:success = mkdir rmdir read write rename
    full_audit:failure = connect
    full_audit:facility = local5
    full_audit:priority = notice

[ebooks]
    path = /libraryit/ebooks
    valid users = @staff, @readonly
    write list = @staff
    browseable = yes

[papers]
    path = /libraryit/papers
    valid users = @staff, @readonly
    write list = @staff
    browseable = yes

[sourcecode]
    path = /libraryit/sourcecode
    valid users = @staff
    # 'browseable = no' bisa digunakan, atau batasi akses di level izin direktori 
    # agar readonly mendapat pesan NT_STATUS_ACCESS_DENIED
    browseable = yes 

[docs]
    path = /libraryit/docs
    valid users = @staff, @readonly
    write list = librarian
    browseable = yes